package com.example.smsfiltering.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.smsfiltering.table.KeyWord;
import com.example.smsfiltering.table.SMS;
import com.example.smsfiltering.table.User;

import com.example.smsfiltering.greendao.KeyWordDao;
import com.example.smsfiltering.greendao.SMSDao;
import com.example.smsfiltering.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyWordDaoConfig;
    private final DaoConfig sMSDaoConfig;
    private final DaoConfig userDaoConfig;

    private final KeyWordDao keyWordDao;
    private final SMSDao sMSDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyWordDaoConfig = daoConfigMap.get(KeyWordDao.class).clone();
        keyWordDaoConfig.initIdentityScope(type);

        sMSDaoConfig = daoConfigMap.get(SMSDao.class).clone();
        sMSDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        keyWordDao = new KeyWordDao(keyWordDaoConfig, this);
        sMSDao = new SMSDao(sMSDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(KeyWord.class, keyWordDao);
        registerDao(SMS.class, sMSDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        keyWordDaoConfig.clearIdentityScope();
        sMSDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public KeyWordDao getKeyWordDao() {
        return keyWordDao;
    }

    public SMSDao getSMSDao() {
        return sMSDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
