package com.example.smsfiltering.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.smsfiltering.table.SMS;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SMS".
*/
public class SMSDao extends AbstractDao<SMS, Long> {

    public static final String TABLENAME = "SMS";

    /**
     * Properties of entity SMS.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SmsId = new Property(0, Long.class, "smsId", true, "_id");
        public final static Property Id = new Property(1, Long.class, "id", false, "ID");
        public final static Property Sender = new Property(2, String.class, "sender", false, "SENDER");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property Time = new Property(4, String.class, "time", false, "TIME");
        public final static Property ReadType = new Property(5, int.class, "readType", false, "READ_TYPE");
        public final static Property UsefulType = new Property(6, int.class, "usefulType", false, "USEFUL_TYPE");
    }


    public SMSDao(DaoConfig config) {
        super(config);
    }
    
    public SMSDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SMS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: smsId
                "\"ID\" INTEGER," + // 1: id
                "\"SENDER\" TEXT," + // 2: sender
                "\"CONTENT\" TEXT," + // 3: content
                "\"TIME\" TEXT," + // 4: time
                "\"READ_TYPE\" INTEGER NOT NULL ," + // 5: readType
                "\"USEFUL_TYPE\" INTEGER NOT NULL );"); // 6: usefulType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SMS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SMS entity) {
        stmt.clearBindings();
 
        Long smsId = entity.getSmsId();
        if (smsId != null) {
            stmt.bindLong(1, smsId);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String sender = entity.getSender();
        if (sender != null) {
            stmt.bindString(3, sender);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
        stmt.bindLong(6, entity.getReadType());
        stmt.bindLong(7, entity.getUsefulType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SMS entity) {
        stmt.clearBindings();
 
        Long smsId = entity.getSmsId();
        if (smsId != null) {
            stmt.bindLong(1, smsId);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String sender = entity.getSender();
        if (sender != null) {
            stmt.bindString(3, sender);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
        stmt.bindLong(6, entity.getReadType());
        stmt.bindLong(7, entity.getUsefulType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SMS readEntity(Cursor cursor, int offset) {
        SMS entity = new SMS( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // smsId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sender
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // content
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // time
            cursor.getInt(offset + 5), // readType
            cursor.getInt(offset + 6) // usefulType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SMS entity, int offset) {
        entity.setSmsId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSender(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setContent(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setReadType(cursor.getInt(offset + 5));
        entity.setUsefulType(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SMS entity, long rowId) {
        entity.setSmsId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SMS entity) {
        if(entity != null) {
            return entity.getSmsId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SMS entity) {
        return entity.getSmsId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
